dont commit changes

diff --git a/.github/workflows/Main Workflow.yml b/.github/workflows/Main Workflow.yml
--- a/.github/workflows/Main Workflow.yml
+++ b/.github/workflows/Main Workflow.yml
@@ -42,33 +42,33 @@ jobs:
     - name: Run Process Raw Filters
       run: python Process_Raw_Filters.py
 
-    - name: Commit and push changes
-      id: push_changes
-      run: |
-        git config --global user.name "github-actions[bot]"
-        git config --global user.email "github-actions[bot]@users.noreply.github.com"
-        git add ADBLOCK_RULE_COLLECTION*.txt timestamp.txt
-        git commit -m "Update Adblock rules" || echo "No changes to commit"
-        for attempt in {1..5}; do
-          echo "Attempt $attempt: Pulling latest changes from remote..."
-          if git pull --rebase; then
-            echo "Pull successful."
-          else
-            echo "Pull failed, continuing..."
-          fi
-
-          if git push; then
-            echo "Push successful."
-            exit 0
-          else
-            echo "Push failed, retrying in $((attempt * 10)) seconds..."
-            sleep $((attempt * 10))
-          fi
-        done
-        echo "Push failed after multiple attempts, exiting with error."
-        exit 1
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#    - name: Commit and push changes
+#      id: push_changes
+#      run: |
+#        git config --global user.name "github-actions[bot]"
+#        git config --global user.email "github-actions[bot]@users.noreply.github.com"
+#        git add ADBLOCK_RULE_COLLECTION*.txt timestamp.txt
+#        git commit -m "Update Adblock rules" || echo "No changes to commit"
+#        for attempt in {1..5}; do
+#          echo "Attempt $attempt: Pulling latest changes from remote..."
+#          if git pull --rebase; then
+#            echo "Pull successful."
+#          else
+#            echo "Pull failed, continuing..."
+#          fi
+#
+#          if git push; then
+#            echo "Push successful."
+#            exit 0
+#          else
+#            echo "Push failed, retrying in $((attempt * 10)) seconds..."
+#            sleep $((attempt * 10))
+#          fi
+#        done
+#        echo "Push failed after multiple attempts, exiting with error."
+#        exit 1
+#      env:
+#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
     - name: Create Release
       id: create_release
